# Generated by Django 4.2.6 on 2024-01-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idColor', models.IntegerField()),
                ('NombreColor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMarca', models.IntegerField()),
                ('NombreMarca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModelo', models.IntegerField()),
                ('NombreModelo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTalla', models.IntegerField()),
                ('NombreTalla', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.IntegerField()),
                ('NombreProducto', models.CharField(max_length=30)),
                ('Imagen', models.ImageField(upload_to='producto')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idColor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.color')),
                ('idMarca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.marca')),
                ('idModelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.modelo')),
                ('idTalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_app.talla')),
            ],
        ),
    ]
